/**
 * Project country list and country → region mapping (Create / Edit Project).
 *
 * Source of truth: scripts/generate-country-region-data.mjs plus world-countries (UN M.49-style
 * subregions) and scripts/country-region-legacy.json (overlay; wins on same country name).
 *
 * Taxonomy: original Sovereign regions are preserved; added Europe sub-buckets, North America,
 * East Asia, Oceania, Antarctica.
 *
 * Regenerate: npm run generate:countries
 */
export const REGIONS = [
  "West Africa",
  "East Africa",
  "Southern Africa",
  "North Africa",
  "Central Africa",
  "Latin America & Caribbean",
  "North America",
  "Southeast Asia",
  "South Asia",
  "Central Asia",
  "Middle East",
  "East Asia",
  "Western Europe",
  "Central Europe",
  "Northern Europe",
  "Southern Europe",
  "Eastern Europe",
  "Oceania",
  "Antarctica",
] as const;

export const COUNTRIES: Record<string, string> = {
  "Afghanistan": "South Asia",
  "Åland Islands": "Northern Europe",
  "Albania": "Southern Europe",
  "Algeria": "North Africa",
  "American Samoa": "Oceania",
  "Andorra": "Southern Europe",
  "Angola": "Southern Africa",
  "Anguilla": "Latin America & Caribbean",
  "Antarctica": "Antarctica",
  "Antigua and Barbuda": "Latin America & Caribbean",
  "Argentina": "Latin America & Caribbean",
  "Armenia": "Middle East",
  "Aruba": "Latin America & Caribbean",
  "Australia": "Oceania",
  "Austria": "Central Europe",
  "Azerbaijan": "Middle East",
  "Bahamas": "Latin America & Caribbean",
  "Bahrain": "Middle East",
  "Bangladesh": "South Asia",
  "Barbados": "Latin America & Caribbean",
  "Belarus": "Eastern Europe",
  "Belgium": "Western Europe",
  "Belize": "Latin America & Caribbean",
  "Benin": "West Africa",
  "Bermuda": "North America",
  "Bhutan": "South Asia",
  "Bolivia": "Latin America & Caribbean",
  "Bosnia and Herzegovina": "Southern Europe",
  "Botswana": "Southern Africa",
  "Bouvet Island": "Antarctica",
  "Brazil": "Latin America & Caribbean",
  "British Indian Ocean Territory": "East Africa",
  "British Virgin Islands": "Latin America & Caribbean",
  "Brunei": "Southeast Asia",
  "Bulgaria": "Southern Europe",
  "Burkina Faso": "West Africa",
  "Burundi": "East Africa",
  "Cambodia": "Southeast Asia",
  "Cameroon": "Central Africa",
  "Canada": "North America",
  "Cape Verde": "West Africa",
  "Caribbean Netherlands": "Latin America & Caribbean",
  "Cayman Islands": "Latin America & Caribbean",
  "Central African Republic": "Central Africa",
  "Chad": "Central Africa",
  "Chile": "Latin America & Caribbean",
  "China": "East Asia",
  "Christmas Island": "Oceania",
  "Cocos (Keeling) Islands": "Oceania",
  "Colombia": "Latin America & Caribbean",
  "Comoros": "East Africa",
  "Cook Islands": "Oceania",
  "Costa Rica": "Latin America & Caribbean",
  "Côte d'Ivoire": "West Africa",
  "Croatia": "Southern Europe",
  "Cuba": "Latin America & Caribbean",
  "Curaçao": "Latin America & Caribbean",
  "Cyprus": "Southern Europe",
  "Czechia": "Central Europe",
  "Democratic Republic of the Congo": "Central Africa",
  "Denmark": "Northern Europe",
  "Djibouti": "East Africa",
  "Dominica": "Latin America & Caribbean",
  "Dominican Republic": "Latin America & Caribbean",
  "Ecuador": "Latin America & Caribbean",
  "Egypt": "North Africa",
  "El Salvador": "Latin America & Caribbean",
  "Equatorial Guinea": "Central Africa",
  "Eritrea": "East Africa",
  "Estonia": "Northern Europe",
  "Eswatini": "Southern Africa",
  "Ethiopia": "East Africa",
  "Falkland Islands": "Latin America & Caribbean",
  "Faroe Islands": "Northern Europe",
  "Fiji": "Oceania",
  "Finland": "Northern Europe",
  "France": "Western Europe",
  "French Guiana": "Latin America & Caribbean",
  "French Polynesia": "Oceania",
  "French Southern and Antarctic Lands": "Antarctica",
  "Gabon": "Central Africa",
  "Georgia": "Middle East",
  "Germany": "Western Europe",
  "Ghana": "West Africa",
  "Gibraltar": "Southern Europe",
  "Greece": "Southern Europe",
  "Greenland": "North America",
  "Grenada": "Latin America & Caribbean",
  "Guadeloupe": "Latin America & Caribbean",
  "Guam": "Oceania",
  "Guatemala": "Latin America & Caribbean",
  "Guernsey": "Northern Europe",
  "Guinea": "West Africa",
  "Guinea-Bissau": "West Africa",
  "Guyana": "Latin America & Caribbean",
  "Haiti": "Latin America & Caribbean",
  "Heard Island and McDonald Islands": "Antarctica",
  "Honduras": "Latin America & Caribbean",
  "Hong Kong": "East Asia",
  "Hungary": "Central Europe",
  "Iceland": "Northern Europe",
  "India": "South Asia",
  "Indonesia": "Southeast Asia",
  "Iran": "Middle East",
  "Iraq": "Middle East",
  "Ireland": "Northern Europe",
  "Isle of Man": "Northern Europe",
  "Israel": "Middle East",
  "Italy": "Southern Europe",
  "Jamaica": "Latin America & Caribbean",
  "Japan": "East Asia",
  "Jersey": "Northern Europe",
  "Jordan": "Middle East",
  "Kazakhstan": "Central Asia",
  "Kenya": "East Africa",
  "Kiribati": "Oceania",
  "Kosovo": "Southern Europe",
  "Kuwait": "Middle East",
  "Kyrgyzstan": "Central Asia",
  "Laos": "Southeast Asia",
  "Latvia": "Northern Europe",
  "Lebanon": "Middle East",
  "Lesotho": "Southern Africa",
  "Liberia": "West Africa",
  "Libya": "North Africa",
  "Liechtenstein": "Western Europe",
  "Lithuania": "Northern Europe",
  "Luxembourg": "Western Europe",
  "Macau": "East Asia",
  "Madagascar": "East Africa",
  "Malawi": "Southern Africa",
  "Malaysia": "Southeast Asia",
  "Maldives": "South Asia",
  "Mali": "West Africa",
  "Malta": "Southern Europe",
  "Marshall Islands": "Oceania",
  "Martinique": "Latin America & Caribbean",
  "Mauritania": "West Africa",
  "Mauritius": "East Africa",
  "Mayotte": "East Africa",
  "Mexico": "Latin America & Caribbean",
  "Micronesia": "Oceania",
  "Moldova": "Eastern Europe",
  "Monaco": "Western Europe",
  "Mongolia": "Central Asia",
  "Montenegro": "Southern Europe",
  "Montserrat": "Latin America & Caribbean",
  "Morocco": "North Africa",
  "Mozambique": "Southern Africa",
  "Myanmar": "Southeast Asia",
  "Namibia": "Southern Africa",
  "Nauru": "Oceania",
  "Nepal": "South Asia",
  "Netherlands": "Western Europe",
  "New Caledonia": "Oceania",
  "New Zealand": "Oceania",
  "Nicaragua": "Latin America & Caribbean",
  "Niger": "West Africa",
  "Nigeria": "West Africa",
  "Niue": "Oceania",
  "Norfolk Island": "Oceania",
  "North Korea": "East Asia",
  "North Macedonia": "Southern Europe",
  "Northern Mariana Islands": "Oceania",
  "Norway": "Northern Europe",
  "Oman": "Middle East",
  "Pakistan": "South Asia",
  "Palau": "Oceania",
  "Palestine": "Middle East",
  "Panama": "Latin America & Caribbean",
  "Papua New Guinea": "Oceania",
  "Paraguay": "Latin America & Caribbean",
  "Peru": "Latin America & Caribbean",
  "Philippines": "Southeast Asia",
  "Pitcairn Islands": "Oceania",
  "Poland": "Central Europe",
  "Portugal": "Southern Europe",
  "Puerto Rico": "Latin America & Caribbean",
  "Qatar": "Middle East",
  "Republic of the Congo": "Central Africa",
  "Réunion": "East Africa",
  "Romania": "Southern Europe",
  "Russia": "Eastern Europe",
  "Rwanda": "East Africa",
  "Saint Barthélemy": "Latin America & Caribbean",
  "Saint Helena, Ascension and Tristan da Cunha": "West Africa",
  "Saint Kitts and Nevis": "Latin America & Caribbean",
  "Saint Lucia": "Latin America & Caribbean",
  "Saint Martin": "Latin America & Caribbean",
  "Saint Pierre and Miquelon": "North America",
  "Saint Vincent and the Grenadines": "Latin America & Caribbean",
  "Samoa": "Oceania",
  "San Marino": "Southern Europe",
  "São Tomé and Príncipe": "Central Africa",
  "Saudi Arabia": "Middle East",
  "Senegal": "West Africa",
  "Serbia": "Southern Europe",
  "Seychelles": "East Africa",
  "Sierra Leone": "West Africa",
  "Singapore": "Southeast Asia",
  "Sint Maarten": "Latin America & Caribbean",
  "Slovakia": "Central Europe",
  "Slovenia": "Central Europe",
  "Solomon Islands": "Oceania",
  "Somalia": "East Africa",
  "South Africa": "Southern Africa",
  "South Georgia": "Antarctica",
  "South Korea": "East Asia",
  "South Sudan": "East Africa",
  "Spain": "Southern Europe",
  "Sri Lanka": "South Asia",
  "Sudan": "North Africa",
  "Suriname": "Latin America & Caribbean",
  "Svalbard and Jan Mayen": "Northern Europe",
  "Sweden": "Northern Europe",
  "Switzerland": "Western Europe",
  "Syria": "Middle East",
  "Taiwan": "East Asia",
  "Tajikistan": "Central Asia",
  "Tanzania": "East Africa",
  "Thailand": "Southeast Asia",
  "The Gambia": "West Africa",
  "Timor-Leste": "Southeast Asia",
  "Togo": "West Africa",
  "Tokelau": "Oceania",
  "Tonga": "Oceania",
  "Trinidad and Tobago": "Latin America & Caribbean",
  "Tunisia": "North Africa",
  "Turkey": "Middle East",
  "Turkmenistan": "Central Asia",
  "Turks and Caicos Islands": "Latin America & Caribbean",
  "Tuvalu": "Oceania",
  "Uganda": "East Africa",
  "Ukraine": "Eastern Europe",
  "United Arab Emirates": "Middle East",
  "United Kingdom": "Northern Europe",
  "United States": "North America",
  "United States Minor Outlying Islands": "North America",
  "United States Virgin Islands": "Latin America & Caribbean",
  "Uruguay": "Latin America & Caribbean",
  "Uzbekistan": "Central Asia",
  "Vanuatu": "Oceania",
  "Vatican City": "Southern Europe",
  "Venezuela": "Latin America & Caribbean",
  "Vietnam": "Southeast Asia",
  "Wallis and Futuna": "Oceania",
  "Western Sahara": "North Africa",
  "Yemen": "Middle East",
  "Zambia": "Southern Africa",
  "Zimbabwe": "Southern Africa",
};

export const COUNTRY_LIST = Object.keys(COUNTRIES).sort((a, b) =>
  a.localeCompare(b, "en")
);
