import { z } from "zod";

/**
 * Validated shape for entities.metadata.
 *
 * Design rules (entity_metadata_v1):
 * - No relational data: type is a column; aliases → entity_aliases;
 *   relationships → entity_relationships; positions → validated_positions.
 * - All facts grounded in Aksum's internal sources only.
 * - Confidence reflects source coverage depth, not claim certainty.
 *
 * Versioned with schema_version so future shape changes can be detected
 * and old rows re-generated by the backfill script.
 */
export const EntityMetadataV1Schema = z.object({
  schema_version: z.literal("entity_metadata_v1"),

  /**
   * 2–8 lowercase, single-word or hyphenated keyword tags.
   * Useful for cross-entity filtering (e.g. "energy", "regulation",
   * "multilateral", "west-africa"). Do not duplicate the entity type here.
   */
  summary_tags: z.array(z.string()),

  /**
   * Country names this entity is associated with based on the sources
   * (e.g. ["Nigeria", "Angola"]). Use full English country names.
   */
  countries: z.array(z.string()),

  /**
   * Economic or thematic sectors this entity operates in or is primarily
   * discussed in relation to (e.g. ["energy", "telecoms", "finance"]).
   */
  sectors: z.array(z.string()),

  /**
   * Overall confidence in this metadata entry based on source coverage.
   * - high: entity is a primary subject in 3+ sources with substantial context.
   * - medium: entity is mentioned materially in 1–2 sources.
   * - low: entity is briefly mentioned; limited grounding.
   */
  confidence: z.enum(["high", "medium", "low"]),

  /** Provenance: how and when this metadata was generated. */
  generated_from: z.object({
    source_count: z.number().int(),
    chunk_count: z.number().int(),
    generated_at: z.string(),
    model: z.string(),
  }),
});

export type EntityMetadataV1 = z.infer<typeof EntityMetadataV1Schema>;

/**
 * The Zod schema passed to generateObject for entity context generation.
 * Does NOT include schema_version or generated_from — those are added
 * programmatically after the LLM call.
 *
 * All fields are required (no .optional()/.nullable()/.default()) to satisfy
 * OpenAI structured outputs' strict mode.
 */
export const EntityContextGenerationSchema = z.object({
  description: z
    .string()
    .describe(
      "Natural-language description of this entity, 200–600 characters. " +
        "Dense but concise. Explain who/what this entity is and why it matters " +
        "in the context of Aksum's internal interview sources. " +
        "Do not end mid-word or mid-sentence. Do not pad with filler phrases."
    ),
  summary_tags: z
    .array(z.string())
    .describe(
      "2–8 lowercase, single-word or hyphenated keyword tags relevant to this entity " +
        "(e.g. 'energy', 'regulation', 'west-africa'). Do not repeat the entity type."
    ),
  countries: z
    .array(z.string())
    .describe(
      "Full English country names this entity is associated with based on the sources. " +
        "Empty array if no country association is grounded."
    ),
  sectors: z
    .array(z.string())
    .describe(
      "Economic or thematic sectors (e.g. 'energy', 'telecoms', 'finance'). " +
        "Empty array if none are clearly grounded."
    ),
  confidence: z
    .enum(["high", "medium", "low"])
    .describe(
      "Overall confidence based on source coverage. " +
        "high = primary subject in 3+ sources; medium = material in 1–2 sources; low = brief mention."
    ),
});

export type EntityContextGeneration = z.infer<typeof EntityContextGenerationSchema>;
