/**
 * Automatically populates `project_entities` rows from `source_entities`
 * after a source is processed through the ingestion pipeline.
 *
 * Called as a best-effort, non-blocking step after all pipeline writes
 * (including `generateSourceEntityContexts`, which populates
 * source_entities.context used here for the note).
 *
 * Entities included:
 *   1. All upload_anchor rows (interviewee, org, participants — user-confirmed).
 *   2. Extraction rows where `is_primary = true` OR `confidence >= 0.9`.
 *
 * The `note` is derived from:
 *   1. `source_entities.context` — source-scoped 1–2 sentence LLM summary
 *      (generated by generateSourceEntityContexts immediately before this).
 *   2. Fallback: entity `description` (first ~250 chars).
 *   3. Otherwise: null.
 *
 * Upsert is idempotent — existing (project_id, entity_id) pairs are
 * silently ignored (ignoreDuplicates: true). Reprocessing a source
 * does not overwrite manually curated notes.
 */

import type { SupabaseClient } from "@supabase/supabase-js";
import type { Database } from "@/types/database";

const NOTE_MAX_CHARS = 300;

function truncateNote(text: string): string {
  if (text.length <= NOTE_MAX_CHARS) return text;
  const cut = text.slice(0, NOTE_MAX_CHARS);
  const lastPeriod = cut.lastIndexOf(". ");
  if (lastPeriod > NOTE_MAX_CHARS / 2) return text.slice(0, lastPeriod + 1);
  const lastSpace = cut.lastIndexOf(" ");
  return lastSpace > NOTE_MAX_CHARS / 3 ? text.slice(0, lastSpace) : cut;
}

/**
 * Upsert `project_entities` rows for a just-processed source.
 * Safe to call on reprocess — duplicate (project_id, entity_id) rows
 * are silently skipped (existing notes are preserved).
 */
export async function writeProjectEntityLinks(args: {
  supabase: SupabaseClient<Database>;
  sourceId: string;
  projectId: string;
  tenantId: string;
}): Promise<void> {
  const { supabase, sourceId, projectId, tenantId } = args;

  // Fetch relevant source_entities rows:
  //   - upload_anchor: user-confirmed entities (primary person, org, participants)
  //   - extraction with is_primary OR confidence >= 0.9
  // Also join entity description for note fallback.
  const { data: seRows, error } = await supabase
    .from("source_entities")
    .select(
      "entity_id, origin, is_primary, confidence, context, entities(description)"
    )
    .eq("source_id", sourceId)
    .or(
      "origin.eq.upload_anchor," +
      "and(origin.eq.extraction,is_primary.eq.true)," +
      "and(origin.eq.extraction,confidence.gte.0.9)"
    );

  if (error) {
    console.error(
      `[project-entity-links] source_entities fetch error for source ${sourceId}:`,
      error
    );
    return;
  }

  if (!seRows || seRows.length === 0) return;

  // Deduplicate by entity_id (an entity may appear in multiple se rows
  // e.g. as both upload_anchor and a later extraction row).
  const seen = new Set<string>();
  const rows: Array<{
    project_id: string;
    entity_id: string;
    tenant_id: string;
    note: string | null;
  }> = [];

  for (const se of seRows) {
    if (seen.has(se.entity_id)) continue;
    seen.add(se.entity_id);

    // Note: prefer source_entities.context; fall back to entity description.
    const entityDesc = (
      se.entities as { description: string | null } | null
    )?.description ?? null;

    const rawNote = se.context ?? entityDesc;
    const note = rawNote ? truncateNote(rawNote) : null;

    rows.push({
      project_id: projectId,
      entity_id: se.entity_id,
      tenant_id: tenantId,
      note,
    });
  }

  if (rows.length === 0) return;

  const { error: upsertError } = await supabase
    .from("project_entities")
    .upsert(rows, { onConflict: "project_id,entity_id", ignoreDuplicates: true });

  if (upsertError) {
    console.error(
      `[project-entity-links] upsert error for project ${projectId}:`,
      upsertError
    );
    return;
  }

  console.log(
    `[project-entity-links] linked ${rows.length} entity/entities to project ${projectId} from source ${sourceId}`
  );
}
