-- Entity type expansion V1
-- Additive only: keep all legacy entity_type values valid.

ALTER TYPE entity_type ADD VALUE IF NOT EXISTS 'COUNTRY';
ALTER TYPE entity_type ADD VALUE IF NOT EXISTS 'SECTOR';
ALTER TYPE entity_type ADD VALUE IF NOT EXISTS 'COMMODITY';
ALTER TYPE entity_type ADD VALUE IF NOT EXISTS 'PUBLIC_INSTITUTION';
ALTER TYPE entity_type ADD VALUE IF NOT EXISTS 'STATE_OWNED_ENTERPRISE';
ALTER TYPE entity_type ADD VALUE IF NOT EXISTS 'LAW_OR_POLICY';
ALTER TYPE entity_type ADD VALUE IF NOT EXISTS 'MEDIA_OR_PUBLICATION';
