-- ============================================================================
-- 00042 — source_entities.context + entity_intel v3
-- ============================================================================
-- Adds a nullable TEXT column `context` to `source_entities` for storing a
-- brief, source-scoped description of why/how an entity relates to a specific
-- source (e.g. "Minister of Finance, discussing the 2026 budget reform").
--
-- This is distinct from `entities.description` (entity-global) and from
-- `source_entities.evidence` (raw extraction quote). It is generated by
-- `generateSourceEntityContexts` in the ingestion pipeline after all chunks,
-- mentions, and relationships have been written.
--
-- entity_intel v3: branch 2 now returns COALESCE(se.context, se.evidence->>'text')
-- as the `evidence` column so the chat tool receives the human-readable context
-- when available, without any change to the RPC's return signature.
--
-- Spec: docs/features/on-going/source-entity-relationship-context.md
-- ============================================================================

-- ── 1. Add context column ────────────────────────────────────────────────────

ALTER TABLE source_entities
  ADD COLUMN IF NOT EXISTS context TEXT;

COMMENT ON COLUMN source_entities.context IS
  'LLM-generated 1–2 sentence description of why/how this entity relates to '
  'this specific source. Distinct from entities.description (entity-global). '
  'NULL for rows written before 00042.';

-- ── 2. entity_intel v3 — surface context via evidence column ────────────────
--
-- COALESCE order: context (rich, generated) > evidence->>'text' (raw extraction
-- quote) > NULL. The RPC return signature is unchanged so the chat tool needs
-- no code changes.

CREATE OR REPLACE FUNCTION public.entity_intel(
  p_entity_id  UUID,
  p_project_id UUID DEFAULT NULL
)
RETURNS TABLE (
  source_id    UUID,
  source_title TEXT,
  role         TEXT,
  kind         TEXT,
  evidence     TEXT,
  chunk_id     UUID,
  sentiment    TEXT,
  conducted_at TIMESTAMPTZ,
  created_at   TIMESTAMPTZ
)
LANGUAGE sql
SECURITY DEFINER
STABLE
SET search_path = public
AS $$
  -- 1) Chunk-level entity mentions (unchanged from v2)
  SELECT s.id              AS source_id,
         s.title            AS source_title,
         'mention'::text    AS role,
         'mention'::text    AS kind,
         c.content          AS evidence,
         em.chunk_id        AS chunk_id,
         em.sentiment       AS sentiment,
         s.conducted_at     AS conducted_at,
         s.created_at       AS created_at
  FROM entity_mentions em
  JOIN sources s              ON s.id = em.interview_id
  LEFT JOIN source_chunks c   ON c.id = em.chunk_id
  WHERE em.entity_id = p_entity_id
    AND (p_project_id IS NULL OR s.project_id = p_project_id)

  UNION ALL

  -- 2) Source-level associations via source_entities (v3 change).
  --    evidence: prefer se.context (generated, human-readable) over the raw
  --    extraction quote in se.evidence->>'text'. Both are nullable.
  SELECT se.source_id,
         s.title AS source_title,
         se.link_type::text AS role,
         CASE se.origin
           WHEN 'upload_anchor'   THEN 'anchor'
           WHEN 'metadata_import' THEN 'anchor'
           WHEN 'manual_tag'      THEN 'anchor'
           WHEN 'human_review'    THEN 'anchor'
           ELSE 'source_entity'
         END AS kind,
         COALESCE(se.context, (se.evidence->>'text')::text) AS evidence,
         NULL::uuid AS chunk_id,
         NULL::text AS sentiment,
         s.conducted_at,
         s.created_at
  FROM source_entities se
  JOIN sources s ON s.id = se.source_id
  WHERE se.entity_id = p_entity_id
    AND (p_project_id IS NULL OR s.project_id = p_project_id)

  UNION ALL

  -- 3) Active relationship edges (unchanged from v2)
  SELECT s.id, s.title, 'related_via_relationship'::text, 'relationship'::text,
         er.evidence_text, NULL::uuid, NULL::text,
         s.conducted_at, s.created_at
  FROM entity_relationships er
  JOIN sources s ON s.id = er.interview_id
  WHERE (er.source_entity_id = p_entity_id OR er.target_entity_id = p_entity_id)
    AND er.review_status <> 'rejected'
    AND (p_project_id IS NULL OR s.project_id = p_project_id);
$$;

COMMENT ON FUNCTION public.entity_intel(UUID, UUID) IS
  'Phase 2.4/v3 RPC for chat entity-centered retrieval. Returns sources where '
  'the entity appears as a chunk-level mention, a source_entities association '
  '(interviewee, author, primary_subject, ...), or a non-rejected relationship. '
  'Branch 2 now returns COALESCE(context, evidence->>text) so generated '
  'source-entity context surfaces automatically. '
  'See docs/features/on-going/source-entity-relationship-context.md.';

REVOKE ALL ON FUNCTION public.entity_intel(UUID, UUID) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.entity_intel(UUID, UUID) TO service_role;
GRANT EXECUTE ON FUNCTION public.entity_intel(UUID, UUID) TO authenticated;
